[package]
name = "rvdasm"
version = "0.1.0"
edition = "2024"

[dependencies]
once_cell = "1.17.0"

[dev-dependencies]
object = "0.36"
clap = { version = "4.5.32", features = ["derive"] }
log = "0.4.20"